default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password
  encoding: unicode
  timeout: 5000
development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test
  password: postgres
production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
