default: &default
  # adapter: postgresql
  # encoding: unicode
  # # For details on connection pooling, see Rails configuration guide
  # # http://guides.rubyonrails.org/configuring.html#database-pooling
  # host: postgres_db
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>​
  # username: postgres
  # password: postgres
  # adapter: postgresql
  # encoding: unicode
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: db
  # username: postgres
  # password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  # timeout: <%= ENV.fetch("DATABASE_TIMEOUT", 5000) %>
  adapter: postgresql
  # username: postgres
  # password: postgres
  # host: postgres_db
  # database: postgres_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  adapter: postgresql
  database: blog_development
  host: postgres_db
  password: postgres
test:
  <<: *default
  database: blog_test
  password: postgres
  host: postgres_db
production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
