name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy_to_heroku:
    name: Deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ancient-escarpment-00115'
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
  integration-test:
    name: Send Request to run Integration Tests
    runs-on: ubuntu-latest
    needs: deploy_to_heroku
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY  }}
          repository: filipgavrilovski/blog_integration_tests
          event-type: cypress-dev
          client-payload: '{ "branch_name": "${{ env.BRANCH_NAME }}", "job_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
