name: Create and publish a Docker image

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: blog-api
  DOCKER_REGISTRY: filipgavrilovski
  # SHA: '$(git rev-parse --short=7 HEAD)'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.docker.outputs.image_tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get tag
        run: |
          tag=$(git rev-parse --short=7 HEAD)
          echo "${tag}" >> $GITHUB_ENV

      - name: Docker Build
        run: |
          echo ${{ env.tag }}
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:id_${{ env.tag }} -f Dockerfile .

      - name: Push to Docker Container
        id: docker
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:id_${{ env.tag }}
          echo "image_tag=id_${{ env.tag }}" >> $GITHUB_OUTPUT
  run-dockerized-tests:
    name: Trigger workflow to run dockerized integration tests
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY  }}
          repository: filipgavrilovski/blog_integration_tests
          event-type: cypress-docker-dev
          client-payload: '{"tag": "${{ env.tag }}", "repository": "${{ github.repository }}"}'
