name: Create and publish a Docker image

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: blog-api
  DOCKER_REGISTRY: filipgavrilovski

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get tag
        id: tag
        run: |
          IMAGE_TAG=$(git rev-parse --short=7 HEAD)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Docker Build
        run: |
          echo ${{ env.IMAGE_TAG }}
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile .

      - name: Push to Docker Container
        id: docker
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  trigger_tests:
    name: Trigger workflow to run dockerized integration tests
    runs-on: ubuntu-latest
    needs: push_to_registry
    env:
      IMAGE_TAG: ${{ needs.push_to_registry.outputs.IMAGE_TAG }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: cypress-docker-dev
          client-payload: '{"tag": "${{ env.IMAGE_TAG }}"}'
