name: Run RSpec tests

on: [push]

jobs:
  cache_ruby_bundle_for_all:
    name: Cache Ruby Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update packages
        run: sudo apt-get update -qq
      - name: Install packages
        run: sudo apt-get -yqq install libpq-dev libcurl4-openssl-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  tests:
    needs: cache_ruby_bundle_for_all
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: postgres
        ports:
          - 5434:5434
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Run tests
        run: |
          bin/rails db:create db:schema:load
          bundle exec rspec
