name: Show results of dockerized integration tests

on:
  repository_dispatch:
    types: [Check Status Of Dockerized Integration Tests]

jobs:
  status_of_tests:
    name: Check status of dockerized integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check for errors in Cypress Execution
        run: |
          if [ ${{ github.event.client_payload.tag }} == 'success' ]; then
            echo "Integration Tests Passed: job url ${{ github.event.client_payload.url }}"
          else
            echo "Integration Tests Failed: job url ${{ github.event.client_payload.url }}"
            exit 1
          fi
      #   run: (if==${{ github.event.client_payload.tag }} && echo "No errors found" || { echo "Error found in the integration tests, expand the previous step ("Check Cypress Execution") to see the error."; exit 1; }
      #   run: echo ${{ github.event.client_payload.tag }}
      # - name: Print url of dockerized tests workflow
      #   run: echo ${{ github.event.client_payload.url }}
