name: Show results of dockerized integration tests

on:
  repository_dispatch:
    types: [Check Status Of Dockerized Integration Tests]

jobs:
  status_of_tests:
    name: UI Integration Specs
    runs-on: ubuntu-latest
    steps:
      - name: Check for errors in Cypress Execution
        run: echo ${{ github.event.client_payload.tag }}
      - name: Print url
        run: echo ${{ github.event.client_payload.url }}
