name: Show results of dockerized integration tests

on:
  repository_dispatch:
    types: [Check Status Of Dockerized Integration Tests]

jobs:
  status_of_tests:
    name: Check status of dockerized integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Print the status
        run: echo ${{ github.event.client_payload.status }}
      - name: Check for errors in Cypress Execution
        run: |
          if [[ ${{ github.event.client_payload.status }} == 'success' ]]; then
            echo "Integration Tests Passed: job url ${{ github.event.client_payload.url }}"
          else
            echo "Integration Tests Failed: job url ${{ github.event.client_payload.url }}"
            exit 1
          fi
      - name: Integration Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.ACTIONS_KEY }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Integration Tests",
            "state": "success",
            "description": "Integration tests passed",
            "target_url": "${{ github.event.client_payload.url }}"
          }'
      - name: Integration Tests 🚨
        if: ${{ failure() }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.ACTIONS_KEY }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Integration Tests",
            "state": "failure",
            "description": "Integration tests failed",
            "target_url": "${{ github.event.client_payload.url }}"
          }'
